services:
  app:
    image: ${DOCKER_USERNAME}/pushinpaybot:${IMAGE_TAG}
    container_name: pushinpaybot
    env_file:
      - .env
    volumes:
      - ./sessions/:/app/sessions/
      - ./logs/:/app/logs/